trigger:
- master

pool: 
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'
  
  
stages:
- stage: build
  jobs:
  - template: template-azure.yml
- stage: dev1
  jobs:
  - template: release-template.yml
    parameters:
      vmImage: ubuntu-18.04
      environmentName: dev1
      location: northeurope
      locationAcronym: eun
      azureSubscriptionServiceConnection: Azure
      dependsOn:
      - build
  
