## ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:
#- task: UseDotNet@2
#  inputs:
#    version: '5.0.x'
#    includePreviewVersions: true # Required for preview versions
#
#- task: UseDotNet@2
#  inputs:
#    version: '3.0.x'
#    packageType: runtime
    
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 2.x
    #performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions  
    
# do this before your build tasks
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
#    feedsToUse: config
#    nugetConfigPath: NuGet.config    # Relative to root of the repository
#    externalFeedCredentials: <Name of the NuGet service connection>#
# ...    

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
    

    

#steps:
# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  


- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
  
  # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'   
  

  
- task: AzurePowerShell@4
  inputs:
    targetType: inline
    azureSubscription: Azure
    azurePowerShellVersion: LatestVersion
    script: |
      New-AzResourceGroup -Name 'Marian' -Location 'norteurope'

