parameters:
- name: vmImage
  type: string
- name: environmentName
  type: string
- name: location
  type: string
- name: locationAcronym
  type: string
- name: azureSubscriptionServiceConnection
  type: string
- name: dependsOn
  type: object


jobs:
- job: FirstApp
  steps:     
  - task: AzurePowerShell@4
    displayName: 'create resource group on Azure'
    inputs:
      scriptType: InlineScript
      azureSubscription: ${{parameters.azureSubscriptionServiceConnection}}
      azurePowerShellVersion: LatestVersion
      inline: |
        New-AzResourceGroup -Name 'app-${{parameters.environmentName}}-${{parameters.locationAcronym}}-rg' -Location '${{parameters.location}}'
