jobs:
- job: FirstApp
  steps:     
  - task: AzurePowerShell@4
    displayName: 'create resource group on Azure'
    inputs:
      scriptType: InlineScript
      azureSubscription: Azure
      azurePowerShellVersion: LatestVersion
      inline: |
        New-AzResourceGroup -Name 'Marian2' -Location 'northeurope'
