jobs:
- job: FirstApp

  steps:      
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 2.x
      #performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions  
      
  # do this before your build tasks
  - task: DotNetCoreCLI@2
    displayName: 'Restore depedence'
    inputs:
      command: restore
      projects: '**/*.csproj'
  #    feedsToUse: config
  #    nugetConfigPath: NuGet.config    # Relative to root of the repository
  #    externalFeedCredentials: <Name of the NuGet service connection>#
  # ...    
  
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)' # Update this to match your need
           
  
  #steps:
  # ...
  # do this after other tasks such as building
  - task: DotNetCoreCLI@2
    displayName: Testing
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    
  
  
  - task: DotNetCoreCLI@2
    displayName: 'Artifact configuration'
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True
    
    # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
  - task: PublishBuildArtifacts@1
    displayName: 'publish Artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'myWebsiteName'   
    
  
    
  - task: AzurePowerShell@4
    displayName: 'create resource group on Azure'
    inputs:
      scriptType: InlineScript
      azureSubscription: Azure
      azurePowerShellVersion: LatestVersion
      inline: |
        New-AzResourceGroup -Name 'Marian2' -Location 'northeurope'
